[phases.setup]
nixPkgs = ['openjdk17']

[phases.build]
cmds = [
  'cd rct-backend',
  'chmod +x gradlew',
  './gradlew bootJar --no-daemon'
]

[start]
cmd = 'cd rct-backend && java -jar build/libs/rct-backend-0.0.1-SNAPSHOT.jar'