[variables]
NIXPACKS_JDK_VERSION = "17"

[phases.setup]
nixPkgs = ["openjdk17"]

[phases.build]
cmds = [
  "cd rct-backend",
  "chmod +x gradlew", 
  "./gradlew clean bootJar --no-daemon --stacktrace"
]

[start]
cmd = "cd rct-backend && java -Dserver.port=$PORT -jar build/libs/rct-backend-0.0.1-SNAPSHOT.jar"