server:
  port: ${PORT:8080}
  address: 0.0.0.0

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
      show-details: never
  health:
    db:
      enabled: false
    redis:
      enabled: false
    mongo:
      enabled: false
    cassandra:
      enabled: false
    elasticsearch:
      enabled: false
    ldap:
      enabled: false

spring:
  application:
    name: rct-backend
  profiles:
    active: railway
  datasource:
    url: ${JDBC_URL:}
    username: ${DB_USER:}
    password: ${DB_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    enabled: false

logging:
  level:
    org.springframework.boot.web.embedded.tomcat: INFO
    org.springframework: INFO
    org.apache.catalina.core.StandardService: INFO
    org.apache.catalina.core.StandardEngine: INFO